import React from 'react';
import { useApp } from '../../context/AppContext';
import { Shield, Lock, FileCheck, PhoneCall, Sparkles, AlertCircle } from 'lucide-react';

export const Footer: React.FC = () => {
  const { navigate, setPrivacyModalOpen, setDemoGuideOpen } = useApp();

  return (
    <footer className="bg-slate-900 text-slate-300 border-t border-slate-800 mt-auto pt-10 pb-8 text-xs">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Core Disclaimer Box - Prominent and High-Contrast */}
        <div className="bg-slate-800/80 rounded-2xl p-4 sm:p-5 border border-slate-700/80 mb-8 shadow-sm">
          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-amber-500/20 border border-amber-500/40 flex items-center justify-center flex-shrink-0 text-amber-400">
              <AlertCircle className="w-5 h-5" />
            </div>
            <div className="space-y-1">
              <div className="text-amber-400 font-bold tracking-wide uppercase text-xs flex items-center gap-2">
                <span>Educational Prototype — Triage Support Only</span>
                <span className="text-[10px] text-slate-400 font-normal normal-case">(BPUT / STISTC Hackathon)</span>
              </div>
              <p className="text-slate-300 text-xs sm:text-sm leading-relaxed">
                Information generated by this system is advisory and must be reviewed by a qualified healthcare professional. 
                This system <strong className="text-white underline decoration-amber-400">does not diagnose conditions</strong> or prescribe treatment.
                All patient profiles and identities displayed are strictly synthetic.
              </p>
            </div>
          </div>
        </div>

        {/* Links & Information Grid */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8 pb-8 border-b border-slate-800">
          
          {/* Col 1: Platform Overview */}
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded-lg bg-teal-500/20 text-teal-400 flex items-center justify-center font-bold">
                SS
              </div>
              <span className="font-extrabold text-white text-sm tracking-tight">SwasthyaSetu AI</span>
            </div>
            <p className="text-slate-400 leading-relaxed text-[11px]">
              Multimodal triage intelligence platform engineered for public healthcare institutions, Primary Health Centres (PHCs), and Community Health Centres (CHCs).
            </p>
            <div className="flex items-center gap-2 text-[11px] text-teal-400 font-semibold">
              <Shield className="w-3.5 h-3.5" />
              <span>Ayushman Bharat Digital Mission (ABDM) Compatible</span>
            </div>
          </div>

          {/* Col 2: Three Core Experiences */}
          <div>
            <h4 className="font-bold text-white uppercase text-[11px] tracking-wider mb-3">Core Interfaces</h4>
            <ul className="space-y-2 text-slate-400 text-xs">
              <li>
                <button onClick={() => navigate('/login')} className="hover:text-cyan-400 transition-colors">
                  1. Secure Authentication & Registration
                </button>
              </li>
              <li>
                <button onClick={() => navigate('/patient/dashboard')} className="hover:text-cyan-400 transition-colors">
                  2. Multilingual Patient Portal
                </button>
              </li>
              <li>
                <button onClick={() => navigate('/doctor/dashboard')} className="hover:text-cyan-400 transition-colors">
                  3. Clinician Triage & Review Hub
                </button>
              </li>
              <li>
                <button onClick={() => navigate('/verify')} className="hover:text-cyan-400 transition-colors">
                  Identity & Credential Verification Sandbox
                </button>
              </li>
            </ul>
          </div>

          {/* Col 3: Privacy & Responsible AI */}
          <div>
            <h4 className="font-bold text-white uppercase text-[11px] tracking-wider mb-3">Responsible AI</h4>
            <ul className="space-y-2 text-slate-400 text-xs">
              <li>
                <button onClick={() => setPrivacyModalOpen(true)} className="hover:text-cyan-400 transition-colors flex items-center gap-1.5">
                  <Lock className="w-3 h-3 text-teal-400" />
                  Privacy Center & RBAC
                </button>
              </li>
              <li>
                <button onClick={() => navigate('/doctor/audit-log')} className="hover:text-cyan-400 transition-colors flex items-center gap-1.5">
                  <FileCheck className="w-3 h-3 text-teal-400" />
                  System Audit Trail
                </button>
              </li>
              <li>
                <button onClick={() => setDemoGuideOpen(true)} className="hover:text-cyan-400 transition-colors flex items-center gap-1.5 text-amber-300 font-medium">
                  <Sparkles className="w-3 h-3" />
                  Judge Walkthrough (14 Steps)
                </button>
              </li>
            </ul>
          </div>

          {/* Col 4: Emergency Assistance */}
          <div>
            <h4 className="font-bold text-white uppercase text-[11px] tracking-wider mb-3">Emergency Helplines</h4>
            <div className="bg-red-950/40 border border-red-800/60 rounded-xl p-3 text-xs space-y-2">
              <div className="flex items-center gap-2 text-red-300 font-bold">
                <PhoneCall className="w-4 h-4 text-red-400 flex-shrink-0" />
                <span>Life-Threatening Emergency</span>
              </div>
              <p className="text-[11px] text-red-200/90 leading-tight">
                For severe breathing distress, unconsciousness, or trauma, immediately dial emergency response:
              </p>
              <div className="flex gap-2 pt-1">
                <span className="bg-red-800/80 text-white font-extrabold px-2 py-0.5 rounded text-xs">108 (Ambulance)</span>
                <span className="bg-red-800/80 text-white font-extrabold px-2 py-0.5 rounded text-xs">112 (National)</span>
              </div>
            </div>
          </div>

        </div>

        {/* Bottom Credits & Copyright */}
        <div className="pt-6 flex flex-col sm:flex-row items-center justify-between gap-3 text-slate-500 text-[11px]">
          <div>
            SwasthyaSetu AI © 2026 — Built for BPUT/STISTC Hackathon.
          </div>
          <div className="flex items-center gap-4">
            <span className="hover:text-slate-400 cursor-pointer" onClick={() => setPrivacyModalOpen(true)}>Privacy Policy</span>
            <span>•</span>
            <span className="hover:text-slate-400 cursor-pointer" onClick={() => setPrivacyModalOpen(true)}>Terms of Prototype</span>
            <span>•</span>
            <span className="hover:text-slate-400 cursor-pointer" onClick={() => navigate('/verify')}>Demonstration Credentials</span>
          </div>
        </div>

      </div>
    </footer>
  );
};
